### ISSUE TITLE
Gui hinterlässt manchmal Prozess

### ISSUE THREAD

**Issue by xeruf** [CAU-Kiel-Tech-Inf/socha-gui#10]
From socha_graphical_client created by [soerendomroes](https://github.com/soerendomroes) : CAU-Kiel-Tech-Inf/socha_graphical_client#43  

![image](https://user-images.githubusercontent.com/6419799/33259643-ce494a6a-d35d-11e7-92c1-c9f6dc603a99.png)

**Comment by xeruf** [comment]
Ich hatte das auch schon unter Linux. Ich habe bisher vergeblich versucht herauszufinden, woran das liegt bzw. wie man es reproduzieren kann.

**Comment by 0xhtml** [comment]
Es handelt sich um den Prozess `java -jar server.jar --port 13050`, der beim Starten der GUI erstellt wird.
Ich konnte dieses Verhalten ebenfalls nicht eindeutig reproduzieren. Ich weiß nur, dass dieses Problem bei mir nach mehreren Spielen, die zum Teil nicht beendet wurden, auftrat.

**Comment by Yasamato** [comment]
Ist das immer noch ein Problem? klingt nach einem Bug bei [socha](https://github.com/CAU-Kiel-Tech-Inf/socha)

**Comment by SKoschnicke** [comment]
Ich denke das tritt noch auf, ja. Aber ist erstmal nicht die Priorität.

**Comment by Yasamato** [comment]
Ich schließe das Issue mal, da dies durch das Upgrade von Electron bereits behoben worden sein könnte. Falls es doch noch auftreten sollte, bitte erneut öffnen
