### ISSUE TITLE
GUI sollte sich bei Fehler nicht aufhängen

### ISSUE THREAD

**Issue by xeruf** [CAU-Kiel-Tech-Inf/socha-gui#100]
Siehe https://github.com/CAU-Kiel-Tech-Inf/socha/issues/242

Wenn der Server einen Fehler zurücksendet, hängt sich die GUI wohl einfach auf.

**Comment by Yasamato** [comment]
Der Server sendet nach jedem Move einen Fehler:
![image](https://user-images.githubusercontent.com/27964795/68243210-53966d00-0012-11ea-8392-c3b1928caa40.png)

Und ich glaube der Server scheint damit nicht klar zu kommen. Die korrekte Verhaltensweise der GUI wäre doch den Spieler anschließend noch mal den Zug auswählen zu lassen oder? Nur bekommt die GUI dann bei jedem möglichen Zug vom Spieler erneut die identische Fehlermeldung:
![image](https://user-images.githubusercontent.com/27964795/68243392-b12ab980-0012-11ea-9eaf-a493e7369915.png)

**Comment by xeruf** [comment]
Wenn ein illegaler Zug gesendet wird, beendet der Server meines Wissens nach das Spiel, also muss es in der GUI auch beendet werden mit dem Hinweis, hier ein Issue zu öffnen.

**Comment by Yasamato** [comment]
Anscheinend beendet der Server das Spiel, aber auch bei allen weiteren Spielen (die vorher und danach erstellt wurden), tritt obige Fehlermeldung dauerhaft mit jedem Zug auf (das unterste Bild)
> [...] Nur bekommt die GUI dann bei jedem möglichen Zug vom Spieler erneut die identische Fehlermeldung:
> ![image](https://user-images.githubusercontent.com/27964795/68243392-b12ab980-0012-11ea-9eaf-a493e7369915.png)

**Comment by Yasamato** [comment]
In #101 enthalten

**Comment by xeruf** [comment]
Oh, dann hätte das eigentlich in der commit message stehen sollen... Naja ^^
