### ISSUE TITLE
Log-Verzeichnis/Datei wird nicht gesetzt

### ISSUE THREAD

**Issue by sw1tchbl4d3r** [CAU-Kiel-Tech-Inf/socha-gui#118]
In Version 20.3.2 vom AppImage wird auf meinem System weder Logdatei noch Logverzeichnis gesetzt. Beides wird bei mir leer angezeigt.
Ich nutze Arch (5.4.6-arch3-1) x86_64.
Es sind noch 2 Screenshots angehangen auf welchen man die leeren Felder sehen kann.
![scr1](https://user-images.githubusercontent.com/54949148/74438757-235d3680-4e6b-11ea-85cb-ec7b2cac00bf.png)

![scr2](https://user-images.githubusercontent.com/54949148/74438758-23f5cd00-4e6b-11ea-8b6a-df36b196e66d.png)

**Comment by Yasamato** [comment]
Ist denke ich trivial, aber nur um sicher zu gehen, hast du als Benutzer, der das Programm ausführt, auch die volle Zugriffsberechtigung auf den Installationsordner?

**Comment by sw1tchbl4d3r** [comment]
Ich denke mal du meinst den Ordner in dem ich das Appimage ausführe/ wo das AppImage sich drin befindet, und ja, ich habe rwx auf dem. Ist in meinem /home

**Comment by sw1tchbl4d3r** [comment]
Nochmal hinzuzufügen: Wenn ich das AppImage als root über sudo starte mit --no-sandbox besteht das Problem.

**Comment by Yasamato** [comment]
Vermutlich ist dies ein Problem mit dem Format von AppImage, da in den anderen Formaten für win/mac scheinbar bisher keine solche Probleme aufgetreten sind.
(Sind letztlich alles Archiv-Dateien, welche ein Dateisystem beinhaltet)

**Comment by xeruf** [comment]
Ja, liegt am AppImage, bei mir passiert genau dasselbe aber es funktioniert wenn ich es von source ausführe.

**Comment by xeruf** [comment]
Okay, da lag ein Programmierfehler meinerseits vor, muss ich mir aber nochmal genauer anschauen.
