### ISSUE TITLE
Grashüpfer können über Beeren springen

### ISSUE THREAD

**Issue by nikohass** [CAU-Kiel-Tech-Inf/socha-gui#120]
Im 1. Replay springt der rote Grashüpfer in Zug 20 über eine Beere.
Im 2. Replay springt der blaue Grashüpfer in Zug 17 über eine Beere.
Im 3. Replay springt der blaue Grashüpfer in Zug 21 über eine Beere.
GUI Version: 20.3.2
[replays.zip](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/files/4236261/replays.zip)

**Comment by nikohass** [comment]
In diesem Freundschaftsspiel hat unser Client in Zug 24 eine Beere übersprungen.

[1582552226_log_188932.xml.zip](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/files/4244883/1582552226_log_188932.xml.zip)

**Comment by nikohass** [comment]
Hier in Zug 22 und 30.

[1582552296_log_188934.xml.zip](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/files/4244906/1582552296_log_188934.xml.zip)

**Comment by xeruf** [comment]
@nikohass in Zukunft am besten auch Screenshots anfügen, dadurch kann man oft auch schon das Problem erkennen, ohne mit den replays hantieren zu müssen ;)

**Comment by xeruf** [comment]
übrigens ist das ein issue im [server](https://github.com/CAU-Kiel-Tech-Inf/socha) - ein gui issue wäre es, wenn die gui einen fehler schmeißt oder was falsch anzeigt ;)

**Comment by xeruf** [comment]
gefixed: https://github.com/CAU-Kiel-Tech-Inf/socha/commit/355c8a3607e0ac27f638233d7989e536b512bf9b
