### ISSUE TITLE
Release ohne builds

### ISSUE THREAD

**Issue by 0xhtml** [CAU-Kiel-Tech-Inf/socha-gui#124]
Dem Release [20.3.4](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/releases/tag/20.3.4) fehlen die Installationsdateien.

**Comment by Yasamato** [comment]
Wird morgen früh behoben

**Comment by Yasamato** [comment]
Korrigiert und erreichbar unter: https://github.com/CAU-Kiel-Tech-Inf/socha-gui/releases/tag/20.3.3

**Comment by 0xhtml** [comment]
Ist es beabsichtigt, dass der Release Java 13 (class file version 57.0) benötigt?
