### ISSUE TITLE
Release 20.3.3 benötigt Java 13

### ISSUE THREAD

**Issue by 0xhtml** [CAU-Kiel-Tech-Inf/socha-gui#126]
Ist es beabsichtigt, dass der Release 20.3.3 Java 13 (class file version 57.0) benötigt?

_Originally posted by @0xhtml in https://github.com/CAU-Kiel-Tech-Inf/socha-gui/issues/124#issuecomment-595424827_

**Comment by Yasamato** [comment]
Mir nicht bekannt, bei mir funktioniert alles noch mit Java 8. Was für ein Betriebssystem benutzt du den @0xhtml? Weißt du da was @Xerus2000?

**Comment by 0xhtml** [comment]
Ich benutze Linux ([elementary OS](https://elementary.io)) mit `openjdk-11-jre` und beim Starten erscheint folgende Fehlermeldung:
![Fehler](https://ucf81448ed79af9bacd725a13fe4.previews.dropboxusercontent.com/p/thumb/AAtxtM0AltxikWpNAN930Ta4XiXIufe2ZlMOJBWmNevUSDzid9gBgMJgtZnNYI5abn5jQ9v_BCOg4JKtqQKp7_GoNxHdeLQ240o8RTzs9mYztqSVBnqkUIb5hyqhvRhWYbW7ysRMkkUJC_iPerYUdeaX5qpV7Iiq_7534MACLJBbCjBqBWjfHNy375RalUNVfwqTP8xIeIFJBUgVyODEBbcTsyuM0JIDFEUWOiwXK_iIlKWL0fhi0zci328pRIhVfsAYcUePMLvvqypKXYz6d9SoGe_4Xsa5ydLRyRe858ADEYJLHv0lpGDyTj5zjbNBaHft0aSCvQETlXczFQHcPJIxFolOCirbWPRl8EPA9nvkPT4uptpqGG1dsdEMnYjbiig32zMdUrqA0a_5uHqvlZom-I7xDqqXiRazMMfnwexvVb_u3AFxSlm81Nsz6XQ8z2Ny-nmh8F2C8nlBoSDmnO5N/p.png?fv_content=true&size_mode=5)
