### ISSUE TITLE
Upgrade Java Version

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/socha-gui#127]
Da Java 8 [Ende 2020](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) keinen (kostenfreien) Support mehr (von Oracle zumindest) bekommt, sollten wir auf mindestens Version 11 setzen (warum nicht gleich 13 oder das bis dahin wahrscheinlich erschienene 14?).

Dies sollte dann natürlich entsprechend beworben werden, damit die Teilnehmer auf die neue Version umsteigen können. Siehe auch https://adoptopenjdk.net/ oder auf [github](https://github.com/AdoptOpenJDK/).

**Comment by Yasamato** [comment]
#128

**Comment by xeruf** [comment]
Das hat nix mit der GUI zu tun und es gibt noch einige Punkte zu besprechen, daher tracken wir das in Notion.
