### ISSUE TITLE
Server-GUI reagiert langsam oder garnicht im Spiel Piranha

### ISSUE THREAD

**Issue by fabianvdW** [CAU-Kiel-Tech-Inf/socha-gui#15]
Betriebssystem: Windows 7 64-Bit
Release: 19.1.2 (auch bereits mehrmals neuinstalliert)
Java-Version: 1.8.0_191-b12 (auch bereits neuinstalliert)

Beim Starten der GUI gibt es keine Probleme. Wenn ich ein Mensch gegen Mensch Spiel starte lädt das Spiel auch nach einigen Sekunden Blackscreen die Animationen und so weiter ein. Ab dann gibt es keine Probleme, bis der erste Zug ausgeführt wird. Der Zug wird erkannt (erstmal nur durch Logs erkennbar), jedoch erfolgt in vielen Fällen keine Antwort des GameManagerWorkerInterface und falls eine Antwort erfolgt, dann erst nach einigen Sekunden(dann wird auch das Spielfeld geupdated). Bei dem ersten Zug erfolgt eine Antwort oft nach ungefähr 30 Sekunden. Weiter als der zweite Zug bin ich noch nicht gekommen.

Log:
![logs](https://user-images.githubusercontent.com/27965216/49174856-87b7d700-f347-11e8-9dc7-91fb98e024f2.PNG)

Zusätzlich werden nach Verlassen des Spielfeldtabs keine Zugmöglichkeiten mehr gelb umrandet, und es ist auch kein Zug mehr ausführbar, die Wasseranimation wird aber immernoch ausgeführt.

![logs2](https://user-images.githubusercontent.com/27965216/49174958-c8afeb80-f347-11e8-8d7e-c16dbceb1c76.PNG)

Zusätzlich gibt es nach dem ersten Schließen eines Spiels (ohne Neustart der GUI) noch weitere Probleme. Soll ein neues Spiel gestartet werden, so muss der "Neues Spiel"-Tab einmal verlassen werden, danach wird das neue Mensch gegen Mensch Spiel angezeigt. Jedoch ist die Spielfeldsituation genau die Ausgangssituation des letzten Spiels, also wird kein neues Spiel geladen und es werden keine gelben Zugkästchen angezeigt.

Log dafür:
![log3](https://user-images.githubusercontent.com/27965216/49175362-b3878c80-f348-11e8-9fd3-6f92d713f22a.PNG)
Spielfeldsituation:
![log4](https://user-images.githubusercontent.com/27965216/49175555-1f69f500-f349-11e8-91d0-1dacfba7c9ec.PNG)

Starte ich das Programm dahingegen auf meiner Ubuntu-VM ist das Spiel einwandfrei spielbar, es muss also an meiner lokalen Windowsinstallation liegen. Leider habe ich keine Ahnung, wieso der Fehler auftritt.
-Fabian vdW

**Comment by xeruf** [comment]
Ich probieren es demnächst mal in Windows. Könntest du die gesamten Logs senden?

**Comment by fabianvdW** [comment]
Hier der Log den ich noch von gestern habe:

[software-challenge-gui-2018.11.28.log.zip](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/files/2629762/software-challenge-gui-2018.11.28.log.zip)

Im Log sind auch einige Fehler erkennbar. Sie finden nach dem Erstellen eines Spiels statt, nach dem ersten "Handling move request" im stdout von dem Server. Bsp:
![fehler](https://user-images.githubusercontent.com/27965216/49239100-2bfe5400-f402-11e8-9b06-87909909580e.PNG)

-Fabian vdW

**Comment by xeruf** [comment]
Dieses Issue ist schon recht alt, ich schließe es mal. Falls weiterhin Probleme auftreten gerne neu öffnen!
