### ISSUE TITLE
Problem mit Gewinnbedingung wenn Schwarm durch fressen des letzten einzelnen Fisches entsteht

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#16]
Erreichte uns von Schuelern:

> beim heutigen Testen der Servers ist uns ein Bug aufgefallen. Wenn der rote Spieler einen Schwarm und zusÃ¤tzlich einen einzelnen Fisch hat, und dieser einzelne Fisch vom anderen Spieler gefressen wird, erscheint keine Gewinnmeldung. Der rote Spieler kann nicht ziehen. Der blaue Spieler hat die Animation fÃ¼r das Ziehen, kann jedoch keine ZÃ¼ge machen. Vermutlich gibt es ein Problem mit der Abfrage, ob ein Spieler nach dem Zug des anderen Spielers gewonnen hat.

Das ist wohl kein Problem mit dem Server, siehe https://github.com/CAU-Kiel-Tech-Inf/socha/issues/198

Also vermute ich, dass nur der Endscreen nicht richtig getriggert wird.

**Comment by 0xhtml** [comment]
Ich kann bestätigen, dass es sich um einen Fehler beim Anzeigen des Gewinners handelt, denn sobald man einmal in ein anderes Spiel (oder auf Neues Spiel etc.) drückt und wieder auf das Spiel zurück geht, wird der Gewinner angezeigt.
(Es wird desweiteren über dem Gewinner auch der Playbutton angezeigt, siehe #6)

**Comment by xeruf** [comment]
Habe es einmal nachgespielt und hatte keine probleme. Bitte wieder öffnen wenn das Problem erneut auftritt,
