### ISSUE TITLE
Auto-updates via electron-builder

### ISSUE THREAD

**Issue by xeruf** [CAU-Kiel-Tech-Inf/socha-gui#2]
Da electron-builder das als feature hat, sollten wir uns das mal anschauen.

**Comment by Yasamato** [comment]
Das muss noch getestet werden... dazu müssten wir aber was auf github releasen

**Comment by Yasamato** [comment]
UI-technisch müsste jetzt nur noch was gemacht werden, die Funktionalitäten sind vorhanden und getestet

**Comment by SKoschnicke** [comment]
Bei mir meldet er sich immer beim Start, dass die Version aktuell ist. Ich finde das ist nur notwendig, wenn es eine neue Version gibt.
