### ISSUE TITLE
Unzuverlässges rendering im viewer

### ISSUE THREAD

**Issue by xeruf** [CAU-Kiel-Tech-Inf/socha-gui#20]
Wenn ich die Geschwindigkeit auf maximal stelle, sieht man im dev log mehrfach pro zug die Warnmeldung "sprite was not on it's place on (x, y)". Gleichzeitig ist die Anzeige im viewer auch sehr sporadisch, Fische verschwinden einfach etc.

**Comment by xeruf** [comment]
@SKoschnicke hast du hier schonmal reingeschaut? Das Problem besteht immer noch.

**Comment by Yasamato** [comment]
Da wir beschlossen haben von der phaser-engine wegzugehen, schließe ich das Issue. Wenn das Problem dann bei der neuen kommenden Implementation für die nächste Saison bitte ein neues Issue mit neuen Infos eröffnen
