### ISSUE TITLE
Endscreen verschwindet nicht wieder, wenn man vom Ende des Spiels zurueckgeht

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#22]
Sobald der Endscreen angezeigt wurde, kann man durch den Zurueckbutton im Spielverlauf zurueck gehen, der Endscreen bleibt aber ueber dem Spielgeschehen. Erst wenn man mit der Leiste links vom Spiel wegspringt (z.B. auf das Serverlog-Fenster) und dann wieder hin, ist der Endscreen weg (und der grosse Play-Button wird angezeigt).

Der Endscreen sollte immer verschwinden, sobald nicht mehr den letzten Zug des Spiels ansieht.

**Comment by xeruf** [comment]
Das Issue hängt damit zusammen dass der Endscreen vom Viewer kontrolliert wird, was mir sowieso nicht so richtig gefällt. Ich schau mal wie sich das machen lässt.
