### ISSUE TITLE
Implementation of GameRuleLogic

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/socha-gui#32]
Am besten nur ein mal die Logic schreiben und von [socha](https://github.com/CAU-Kiel-Tech-Inf/socha) portieren lassen, evtl. als submodul?

**Comment by Yasamato** [comment]
Fürs erste würde ich heute abend eine die Logic als ts implementieren und orientiere mich hierbei am alten [PiranhasGameRules.ts](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/hive/src/api/rules/PiranhasGameRules.ts)

**Comment by SKoschnicke** [comment]
Zusaetzlich solltest du dich an den (hoffentlich heute Abend schon recht weit) implementierten Regeln im Server orientieren: https://github.com/CAU-Kiel-Tech-Inf/socha/blob/hive/plugin/src/shared/sc/plugin2020/util/GameRuleLogic.java
Da kann man eigentlich ganz gut Copy-Paste machen und dann auf Typescript umschreiben.
