### ISSUE TITLE
Missing graphics for grasshopper

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/socha-gui#33]

**Comment by Yasamato** [comment]
Please update [HiveEngine.ts](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/2de43d1ad0018f1762de6e4971a6782d568165f0/src/viewer/Engine/HiveEngine.ts) on [line 40](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/2de43d1ad0018f1762de6e4971a6782d568165f0/src/viewer/Engine/HiveEngine.ts#L40) and [line 111](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/2de43d1ad0018f1762de6e4971a6782d568165f0/src/viewer/Engine/HiveEngine.ts#L111) in viewer as well

**Comment by SKoschnicke** [comment]
https://github.com/CAU-Kiel-Tech-Inf/socha-gui/commit/05945c478e99cdf5070ad2ef78c53f9fda2075d1
