### ISSUE TITLE
Upgrade to Electron 7

### ISSUE THREAD

**Issue by matthesjh** [CAU-Kiel-Tech-Inf/socha-gui#39]
When upgrading Electron to version 6.1 the following packages should also be updated:

- [electron-builder](https://github.com/electron-userland/electron-builder/) to version 21.2.0

**Comment by matthesjh** [comment]
Electron version 7.0 was released yesterday, so it should be considered to update to this newer version.

**Comment by Yasamato** [comment]
Mit https://github.com/CAU-Kiel-Tech-Inf/socha-gui/commit/0796f8226a37d2b337fcd9eff7a1007395e401d2 bereits geschehen, jedoch noch nicht komplett angepasst, aber scheinbar lauffähig
