### ISSUE TITLE
Zwangsausetzen HumanClient

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/socha-gui#42]
Ich konnte bisher kein Szenario erstellen bei dem das der Fall war, aber was dann?

**Comment by xeruf** [comment]
Biene irgendwo setzen, dann eine Ameise setzen, dann hin und her bewegen und dabei mit dem anderen die Ameise von drei Seiten einschließen.
Hm Moment, dann kann man noch die Biene bewegen, Ich zweifle gerade, dass zwangsaussetzen jemals vorkommt, denn dann wäre die Biene ja bewegungsunfähig und damit das Spiel beendet.

**Comment by Yasamato** [comment]
Wenn man nur die Biene setzt, muss diese ja nur von 3 Steinen eingeschlossen werden, wodurch kein weiteres mehr platziert werden könnte, da es keine benachbarten felder gibt, welche nicht direkt mit einem Gegner verbunden sind, was wiederum Zwangsweise zu einer Niederlage führen kann. Aber ja, realistisch gesehen fällt mir da nichts ein, was zu einer Zwangsaussetzung führen könnte, vor allem da im Verlaufe eher mehr Pieces platziert werden und keine entfernt, was nicht heißt dass sie trotzdem eintreten könnten.

**Comment by SKoschnicke** [comment]
Wenn Rot im ersten Zug eine Nicht-Biene in eine Ecke des Spielfeldes setzt und Blau dann daran einen eigenen Spielstein, kann Rot keinen weiteren Stein platzieren (wuerde immer den blauen Stein beruehren) und muss somit aussetzen.
Wir brauchen also eine Aussetz-Funktion. Wird vom Server auch noch nicht unterstuetzt.

https://github.com/CAU-Kiel-Tech-Inf/socha/issues/222

**Comment by Xerus2000** [comment]
aber Rot kann doch den gesetzten Stein noch bewegen?

**Comment by Yasamato** [comment]
Dass geht nur wenn bereits eine Bee platziert wurde, wenn es keine ist, dann kann Blau Rot dazu zwingen nie mehr eine Figur zu setzen
