### ISSUE TITLE
Bug-collector

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/socha-gui#43]
### Known Bugs:
- none 😄 

### Wichtige Erweiterungen:
- [ ] Zuganimationen #57 

### Und serverseitig fehlt desweiteren noch:
- Spielende mit der 31. Runde
- Unentschieden erkennen

### Muss noch getestet werden:
- [x] Zwangsausetzen bei Human-Client #42
- [ ] Unentschieden

**Comment by SKoschnicke** [comment]
Ist dieses Ticket weiterhin sinnvoll? Ich denke die Suche mit Milestones und Tags ist besser, da sie sich automatisch aktualisiert: 

https://github.com/CAU-Kiel-Tech-Inf/socha-gui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug

https://github.com/CAU-Kiel-Tech-Inf/socha-gui/issues?q=is%3Aissue+is%3Aopen+label%3Abug+milestone%3A20.0.0
