### ISSUE TITLE
Game stellt Map mit Coords anders dar

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/socha-gui#46]
Das Spiel stellt aktuell die Map folgendermaßen dar mit den Coords (q, r) aka (x, y):
![image](https://media.discordapp.net/attachments/618361705117908992/620705153523384340/unknown.png)

Jedoch wird im Guide unter https://www.redblobgames.com/grids/hexagons/#range-coordinate das mit (x, z, y) aka (q, s, r):
![image](https://user-images.githubusercontent.com/27964795/64562349-1e8cd780-d34d-11e9-8fdc-e85c6a648522.png)

Ist das ein Problem? Haben wir bei der Datenstruktur irgendwas verkackt oder wird bei der Feld-Generierung einfach nur anders vorgegangen.

**Comment by SKoschnicke** [comment]
Ich glaube da ist nichts falsch. Das Spielfeld wird nur an der x-Achse gespiegelt dargestellt.

**Comment by xeruf** [comment]
Es ist senkrecht zur x-Achse gespiegelt. Das ist halt beim tests debuggen total verwirrend, aber erstmal nur was grafisches.

**Comment by xeruf** [comment]
https://www.redblobgames.com/grids/hexagons/ wir haben bei den Koordinaten was falsch gemacht: q und r sollten mit x und z übereinstimmen, wir nutzen aber überall x und y. Das müssen wir morgen nochmal besprechen.

**Comment by SKoschnicke** [comment]
In den meisten Beispielen auf der Seite wird x q und z r zugeordnet, aber das ist nicht zwingend und macht die anderen Zuordnungen nicht falsch:

> There are many choices of cube coordinate system, and many choices of axial coordinate system. I'm not going to show all of the combinations in this guide. I've chosen q for "column" = x and r as "row" = z. This choice is arbitary, as you can rotate and flip the diagrams to make many different assignments of ±x,±y,±z to q,r.

https://www.redblobgames.com/grids/hexagons/#coordinates-axial

Ich vermute daher unsere Koordinaten sind nur nicht konsistent mit dem Beispielbild von der RedBlobGames Seite, aber zwischen Server und GUI schon. Ich pruefe das heute aber nochmal.

**Comment by SKoschnicke** [comment]
behoben durch 977e695
