### ISSUE TITLE
Fehler bei Anzeige von moeglichen Zielfeldern fuer Ameise

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#49]
![img-2019-09-10-205121](https://user-images.githubusercontent.com/105162/64641742-198f5d00-d40d-11e9-91cd-14ccf6891d25.png)

Ausgewaehlt wurde die rote Ameise auf 0,2. Sie sollte auch auf 1,0; 2,-1 usw. koennen.

**Comment by Yasamato** [comment]
Auch hier scheint der Server bei manchen Szenarien keinen State zu updaten oder turn++

**Comment by SKoschnicke** [comment]
Die Anzeige der Zielfelder liegt aber nicht am Server. Ist immernoch nicht richtig:
![img-2019-09-12-201254](https://user-images.githubusercontent.com/105162/64809559-e4fcdc00-d599-11e9-83a4-f305224a29fe.png)
(habe die rote Ameise angewaehlt)

**Comment by Yasamato** [comment]
Oh ja, hab vergessen abzufragen ob es ein Randtile ist.

**Comment by Yasamato** [comment]
Oh... hab das ausversehen automatisch geclosed, ohne zu testen, ob das im Server schon funktioniert, aber es sieht bisher gut aus 👍

**Comment by SKoschnicke** [comment]
Bitte nochmal im Server gucken, ob das korrekt ist.

**Comment by xeruf** [comment]
Bitte im Server ein konkretes issue öffnen wenn noch was falsch ist.

**Comment by Yasamato** [comment]
Hm es ist auch noch in der gui irgendwas falsch... schau morgen drüber.
![image](https://user-images.githubusercontent.com/27964795/64898094-25d21f00-d686-11e9-9ee8-68664773868c.png)

**Comment by SKoschnicke** [comment]
Das auf dem Bild sieht für mich richtig aus, was ist da falsch?

**Comment by Yasamato** [comment]
Wenn die Ameise auf -1,2 zieht, kann sie auch auf -2,3 anschließend ziehen und so weiter, da dies immer verbunden ist und am Rand des Schwarms
