### ISSUE TITLE
Kaefer kann nicht auf anderen Stein ziehen, wenn rechts und links die Felder leer sind

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#50]
![img-2019-09-10-213708](https://user-images.githubusercontent.com/105162/64644593-4181bf00-d413-11e9-96da-16b31fe30346.png)
roter Kaefer auf 0,1 ist angeklickt, sollte auf die Biene ziehen koennen.

**Comment by Yasamato** [comment]
Ist es serverseitig bereits implementiert?

**Comment by xeruf** [comment]
ah ja, ich weiß woran es liegt ^^

**Comment by xeruf** [comment]
gefixt in https://github.com/CAU-Kiel-Tech-Inf/socha/commit/ee15604617bcbf41d507092c1c6effaf6b5d9760
