### ISSUE TITLE
Anzeige einer Regelverletzung bei menschlichen Spielern

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#51]
Wenn man ueber die GUI als Mensch spielt und einen ungueltigen Zug eingibt, kommt die GUI in einen Zustand, wo keine Eingaben mehr moeglich sind. Anscheinend wird auch extrem viel gepollt, was die CPU-Last hochtreiben duerfte.
Natuerlich passiert das nur, wenn die GUI ungueltige Eingaben nicht vorher abfaengt, aber es hat sich beim Testen als sehr hinderlich erwiesen. Und man kann nie ausschliessen, dass Randfaelle uebersehen werden. In den Faellen sollte man wenigstens entsprechendes Feedback bekommen.

**Comment by Yasamato** [comment]
Hm... ich habe jetzt mal eine ganze Weile herum geforscht wie man es tun sollte (mit electron via ipc ein event triggern, dass dann eine ErrorBox anzeigt, die dialog.showErrorBox direkt aufrufen etc...), ich kann aber leider nur von `PlayerClient.ts` aus nicht auf electron samt seinen Modulen zugreifen (alles undefined...), daher fallen leider alle Optionen eine einfache Fehlermeldung im Dialog anzeigenzulassen via electron ins Wasser wenn ich das richtig sehe beim momentanen Stand.

**Comment by SKoschnicke** [comment]
Ich glaube nicht, dass man da irgendwas an der aktuellen Kommunikation zwischen Node (Backend der GUI) und Browser machen muss. Das Spiel wird vom Server wegen einer Regelverletzung beendet und der GameManager der GUI bekommt das auch mit. Was nur nicht passiert, ist dass der Endscreen dann angezeigt wird. Ich glaube dass das Anzeigen des Endscreens aber grundsaetzlich funktioniert, es hat zumindest in den letzten Jahren funktioniert. Nur in Spielen Mensch gegen Mensch wurde das eventuell nie getestet, da man dort keine ungueltigen Zuege abschicken konnte.

**Comment by SKoschnicke** [comment]
Dieser Bug behindert das manuelle Testen sehr stark, da sich die GUI nach dem Beenden des Spiels durch den Server nicht mehr konsistent verhaelt und wir dadurch Bugreports bekommen, die auf andere Fehler hindeuten, aber eigentlich eine Beendigung des Spiels durch den Server *vorher* als Ursache haben.

**Comment by Yasamato** [comment]
Hm ich kann deine Beschreibung nicht reproduzieren... aber ich denke, dass du etwas in diese Richtung meintest? Was mir bekannt war, war dass nach dem senden des Moves, der Server mit einem leeren gamestate antwortet

**Comment by SKoschnicke** [comment]
Das ist definitiv schonmal eine Hilfe, super! Ich meinte aber eigentlich die Anzeige ganz normal ueber den Endscreen. Vielleicht ist das auch ein Problem beim Server, warum das noch nicht geht. Koennen wir erstmal so lassen.
