### ISSUE TITLE
Anpassung des XML-Parsens der GUI

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#52]
Im XML werden die x,y,z Koordinaten jetzt als Attribute statt als Kind-Tags uebertragen. Das muss im `fromJson` des Boards sowie in der generierung des Move-XML in `HumanClient.ts` noch angepasst werden.

**Comment by Yasamato** [comment]
Hm... @SKoschnicke wenn ich das richtig sehe, wird das serverseitig weiterhin als subtags im server gelesen und geparst, kannst du mir den entsprechenden Server-Code zeigen was du damit meinst?

**Comment by SKoschnicke** [comment]
Die Änderung ist im branch `hive_xml_break`

**Comment by Yasamato** [comment]
Hm... abgesehen davon, dass der Server jetzt nicht mal mehr startet, kommt es immer zu der Fehlermeldung.
![image](https://user-images.githubusercontent.com/27964795/64819246-1e3f4700-d5ae-11e9-9c6b-370d55ddea06.png)

 Aber sehe ich das richtig, dass in `Hive.ts` bereits die Koordinaten via attributs ausgelesen werden?
