### ISSUE TITLE
Gestartetes GUI hat einen Fehler beim Game-Server

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha-gui#65]
Hallo,
ich versuche für die Videos zur Software Challenge ein GUI für Piranhas zu erstellen, welches die Feldmarkierungen nicht mehr hat. Ich habe also die Grafik komplett durchsichtig gemacht. Dann erstelle ich das Appimage, da ich unter Linux arbeite. Beim Start des Images bekomme ich dann den Fehler : "Es gab einen fehler beim Start des Game-Servers, das Programm wird wahrscheinlich nicht funktionieren." . Ich mache bestimmt was recht dummes falsch, ich kenne mich aber auch nicht mit den Tools und TypeScript aus. Wäre nett, wenn du mir da etwas helfen könntest.

**Comment by SKoschnicke** [comment]
Der Server ist ein Git Submodule, welches im GUI-Projekt im Verzeichnis `socha` liegt.

Ich denke da fehlt nur ein `yarn update-server` bevor du `yarn dist -l` machst, um das Appimage zu bauen. Alternativ musst du auch kein kein Image bauen sondern kannst die Anwendung direkt mit `yarn start` starten (aber das update-server in jedem Fall vorher ausfuehren).

**Comment by sunfl0w** [comment]
Danke. Über "yarn start" funktioniert es jetzt.
