### ISSUE TITLE
Die Vorversion des GUIs funktioniert nicht (richtig) unter Linux.

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha-gui#66]
Das GUI funktioniert unter Linux noch nicht so recht. Zuerst kam die Fehlermeldung: 
<details><summary>Klick</summary>
<p>

**[7067:0915/170031.873898:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Test.AaYzNsf/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)**

</p>
</details>

Durch diesen Thread konnte ich erstmal dieses Problem lösen: https://github.com/electron/electron/issues/17972

Danach startet das GUI mit einem weißen Fenster im Hintergrund auf dem Fehler angezeigt werden. Im Vordergrund kann man dann wie erwartet spielen. Schließen lässt sich das Fenster dann nur, indem man den dazugehörigen Prozess killt.

**Comment by Yasamato** [comment]
Hm bei der Ausführung via `yarn start` oder mit dem AppImage? Welche Vorversion meinst du, die Hive-beta?
Aber da kann ich dir auch wenig helfen, da das ein Problem mit der Unix-Berechtigung anscheinend ist.

Falls du Arch benutzt, könnte das die [Lösung](https://github.com/electron/electron/issues/17972#issuecomment-486927073) sein, ansonsten habe ich selbst momentan kein Setup um das nachzuvollziehen. @SKoschnicke vielleicht?
Andere möglichkeit, wenn du das mit `yarn start` machst, wäre den Parameter [--no-sandbox](https://github.com/electron/electron/issues/17972#issuecomment-526532204) zu benutzen, welcher eigentlich aus Sicherheitsgründen vermieden werden sollte..

**Comment by sunfl0w** [comment]
Ich meine das GUI-AppImage für Hive. Ich lade mir sonst nochmal das Reposetory runter und teste über yarn start.

**Comment by SKoschnicke** [comment]
Das Appimage sollte schon funktionieren. Ich schaue mir das an.

**Comment by sunfl0w** [comment]
Wenn ich das GUI über yarn start aufrufe klapp alles wie es sollte. Nur beim AppImage habe ich Probleme.

**Comment by sunfl0w** [comment]
Das Problem scheint mit der dritten Hive-Beta behoben zu sein.
