### ISSUE TITLE
Resourcenverbrauch senken

### ISSUE THREAD

**Issue by xeruf** [CAU-Kiel-Tech-Inf/socha-gui#7]
From socha_graphical_client created by [SKoschnicke](https://github.com/SKoschnicke) : CAU-Kiel-Tech-Inf/socha_graphical_client#78  

Bei mir verbraucht die GUI im Leerlauf (also waehrend sie auf die Zugeingabe eines menschlichen Spielers wartet) mit drei Threads zwischen 17 und 27% CPU. Das finde ich zu viel, selbst fuer eine Electron App. Wahrscheinlich hilft es schon, wenn wir nicht dauernd nach dem Server Status pollen.

**Comment by Yasamato** [comment]
Im Leerlauf ohne ein Spiel offen, komme ich auf um die 3% Auslastung während ich mit geöffnetem Spiel auf 6 Threads (sind immer 6 Threads) mit peaks bis zu 10% komme.

**Comment by SKoschnicke** [comment]
Wenn man aber ein Spiel zu Ende gespielt hat, steigt die Last extrem. Beim laufenden Spiel habe ich auch mindestens einen Kern komplett ausgelastet.

**Comment by Yasamato** [comment]
Da dies eigentlich ein Dauerauftrag ist, schließe ich mal das Issue. Falls extreme Leistungsspitzen auftreten sollten, bitte ich dafür ein seperates Issue zu eröffnen, damit gezielt einzelne Leistungsprobleme bearbeitet werden können
