### ISSUE TITLE
Fehler bei Spinnenbewegung

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#73]
![img-2019-09-16-063908](https://user-images.githubusercontent.com/105162/64934711-e86bbe00-d84c-11e9-8460-fa6a205f4ae8.png)
Die blaue Spinne muesste auch auf 0,3 ziehen koennen (0,1 -> 0,2 -> 0,3).

**Comment by Yasamato** [comment]
Ich schau mir das mal an
