### ISSUE TITLE
Fehler bei Ameisenbewegung

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#74]
![img-2019-09-16-064542](https://user-images.githubusercontent.com/105162/64934839-c6267000-d84d-11e9-96eb-852561e2159e.png)
Die obere blaue Ameise darf nicht an der Himbeere auf 1,-1 vorbei nach unten. Die sollte fuer die Bewegung wie ein leeres Feld zaehlen. So wie -1,-1 fuer die untere blaue Ameise:
![img-2019-09-16-064526](https://user-images.githubusercontent.com/105162/64934885-f5d57800-d84d-11e9-940a-9933f040eb60.png)

**Comment by Yasamato** [comment]
Nein, ich glaube das ist korrekt, da die Ameise den kompletten weg anders herum da hin gehen kann auf die Andere Seite der Frucht

**Comment by SKoschnicke** [comment]
Du hast recht, sehr gut.
