### ISSUE TITLE
Tests implementieren

### ISSUE THREAD

**Issue by Yasamato** [CAU-Kiel-Tech-Inf/socha-gui#78]
**Das ist hier einfach eine Brainstorm-Liste, was alles zu testen ist**

### Get possible moves
- [ ] Possible moves bei Ant
- [x] Possible moves bei Bee
- [ ] Possible moves bei Beetle
- [ ] Possible moves bei Grasshopper
- [ ] Possible moves bei Spider
- [ ] Possible moves bei empty
- [ ] Possible moves bei obstructed
- [ ] Possible moves bei outside board

### Validate moves
- [ ] Validate moves bei Ant
- [ ] Validate moves bei Bee
- [ ] Validate moves bei Beetle
- [ ] Validate moves bei Grasshopper
- [ ] Validate moves bei Spider
- [ ] Validate moves bei empty
- [ ] Validate moves bei obstructed
- [ ] Validate moves bei outside board

### Board
- [ ] Coordinate isOnBoard
- [x] Clones correctly
- [ ] SHIFT, FIELDSIZE -> count total fields != null
- [ ] Get field
- [ ] Get fields by color
- [ ] Get fields by color and type
- [ ] Get top-piece of field

### GameRule
- [ ] Get neighbours
- [ ] Is path obstructed to neighbour
- [ ] Is Coordinate in line with other Coordinate
- [x] Is swarm connected with obstructed field disconnecting it
- [x] Is swarm connected while being disconnected
- [x] Is swarm connected while being connected

**Comment by SKoschnicke** [comment]
Zusaetzlich kann man die Tests aus dem Server mit minimalen Anpassungen uebernehmen.

**Comment by SKoschnicke** [comment]
Das ist erstmal gut so. Es sollten Tests hinzugefuegt werden, wenn sich konkrete Fehler zeigen.
