### ISSUE TITLE
Bereits beendetes Spiel erscheint beim Neustart

### ISSUE THREAD

**Issue by fwcd** [CAU-Kiel-Tech-Inf/socha-gui#81]
Nach dem Neustart eines Spieles, erscheint nach dem ersten Zug das Spielbrett der letzten Runde:

![screencast](https://user-images.githubusercontent.com/30873659/65196791-eab65e00-da80-11e9-9606-cb4293c8258c.gif)

**Comment by Yasamato** [comment]
Hm... @SKoschnicke die GUI scheint das richtig zu fetchen wenn ich das richtig sehe, ist das ein Problem beim Server?

**Comment by SKoschnicke** [comment]
@fwcd vielen Dank fuer die tolle Videobeschreibung!

@Agent77326 das Problem liegt vermutlich beim GameManager der GUI. Definitiv nicht beim Java Server. Es ist ja im Moment auch so, dass wenn man von einem auf ein anderes Spiel wechselt und dann wieder zurueck er den aktuellen Zug nicht behaelt sondern wieder von 0 anfaengt. Vielleicht gibt es da sogar einen Zusammenhang.

**Comment by Yasamato** [comment]
~Das Problem lag glaube ich daran, dass wir manuell das Spiel in der GUI gestartet hatten. Durch entfernen entsprechendes Codes, konnte ich das Verhalten nicht mehr reproduzieren~
Ich glaube ich weiß wo der Fehler liegt, nur nicht warum er auftritt..

**Comment by Yasamato** [comment]
Steps zur Reproduktion:

1. Die GUI neu öffnen
2. "Neues Spiel"
3. Spieler 1 (Rot) muss ein com sein und Spieler 2 Mensch

Bis hier funktioniert alles wie erwartet, tätige paar Züge etc. (funktioniert auch direkt ohne weitere Züge)

4. "Neues Spiel"
5. Spieler 1 (Rot) muss ein com sein und Spieler 2 Mensch

Hier wird ein neues Spielfeld erwartet, jedoch wird das GameState vom vorherigen Spiel angezeigt. In der console ist auch vermerkt, dass deepEqual der aktuellen renderstate mit dem gegebenen neuen übereinstimmt, jedoch ist dies nicht der Fall, wird aber durch eine weitere Action richtig ausgelöst.

Was aber komisch ist, dass manchmal direkt ein neues Feld generiert und angezeigt wird, jedoch der Zug des coms nicht angezeigt wird, bei einer 2. Interaction (Klick irgendwo hin), wird das vorherige Spielfeld jedoch angezeigt. Wenn man aber links auf das Spiel klickt in der Leiste unter "Replay laden", wird das richtige Brett angezeigt und alles funktioniert wie erwartet.

Mögliche Probleme wären:
- Falsches Handling der RoomId(GameId) o. kein update
- Angeforderte User-Interaction mit altem Gamestate werden nicht gecancelt und neu aufgerufen, sodass der alte User-state erneut gerendert wird.
- Fehlendes Clean-Up nach schließen/wechseln eines Spiels(/Replays)
