### ISSUE TITLE
Starten des GUI in Linux mit "--no-sandbox".

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/socha-gui#82]
Ich hatte ja letztens dieses eine Problem beim Starten des GUIs in Linux. Ich wollte hier nochmal anmerken, dass das Problem noch existiert. Nach jedem Neustart meines PCs muss ich erneut einen der Workarounds nutzen. Die eleganteste Lösung bis jetzt ist, das AppImage mit der Option "--no-sandbox" zu starten. Vielleicht sollte dies irgendwo noch als Hinweis auftauchen.

**Comment by xeruf** [comment]
@sunfl0w bitte ergänze hier im issue nochmal eine erläuterung des Problems, kann auch einfach kopiert sein, damit man nicht erst discord durchsuchen muss

**Comment by sunfl0w** [comment]
Ich kann den Fehler tatsächlich nicht mehr reproduzieren mit der Version 20.0.9 .
Das Problem bestand darin, dass das GUI ohne die Option nicht starten wollte.
Ich habe aber einen weiteren Linux bezogenen gefunden. Dort wird der Game-Server wohl nicht richtig gestartet wird, könnte das damit zusammenhängen, dass ich eine VM benutze, da es auf dem Desktop funktioniert? Ich würde das dann gegebenenfalls als neues Issue eintragen.

**Comment by xeruf** [comment]
Ja, kannst ein separates issue aufmachen. In einer VM könnte es daran liegen, dass die Ports nicht zugänglich sind die die GUI braucht - warum nutzt du da überhaupt ne VM?

**Comment by sunfl0w** [comment]
Ich wollte das ursprüngliche Problem nochmal reproduzieren, da es auf meinem Desktop nicht mehr auftrat. Testen wollte ich das dann nochmal in einer VM auf meinem Notebook.

**Comment by sunfl0w** [comment]
Welche Ports werden denn benötigt?

**Comment by xeruf** [comment]
13050 bzw 13051 sind Standard, siehe https://cau-kiel-tech-inf.github.io/socha-enduser-docs/server.html#automatische-spiele

**Comment by SKoschnicke** [comment]
Wenn der Server und die GUI-App in der VM laeuft, und das ist der Fall wenn man einfach die GUI startet, sollte das aber kein Problem sein.

**Comment by sunfl0w** [comment]
Interessant. Ich habe versucht die Ports freizumachen, ohne Erfolg. Das GUI kann ich dann also nicht in der VM starten, aber auf meinem Desktop schon.

**Comment by sunfl0w** [comment]
Das mit der VM hat sich erledigt. Ich habe das OpenJDK nochmal neuinstalliert und ein komplettes Systemupdate durchgeführt. Danach läuft jetzt alles wie es sollte.
