### ISSUE TITLE
Aussetzen wird angezeigt, obwohl moegliche Zuege

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#83]
Aussetzen wird in folgender Situation angezeigt:

![aussetzen-fehler](https://user-images.githubusercontent.com/105162/65424621-462f7580-de0c-11e9-8ec7-8c5b66fa9ef9.png)

Anscheinend ist Rot an der Reihe, es gibt aber moegliche Zuege fuer Rot.

**Comment by jnccd** [comment]
Hier ist auch das Replay

[Mensch vs 2.zip](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/files/3642029/Mensch.vs.2.zip)
