### ISSUE TITLE
UndeployedBluePieces werden nicht korrekt geparsed wenn alle roten Pieces bereits gesetzt wurden

### ISSUE THREAD

**Issue by xeruf** [CAU-Kiel-Tech-Inf/socha-gui#85]
Siehe https://github.com/CAU-Kiel-Tech-Inf/socha/issues/225

Habe einen kleinen test geschrieben, am Parser scheints nicht zu liegen:
```js
  undeployedRedPieces: [ '' ],
  undeployedBluePieces: [ { piece: [Array] } ]
```
Ich werde weiter experimentieren.

**Comment by xeruf** [comment]
am xml parser liegts nicht, habe extra nen neuen test gemacht: https://github.com/CAU-Kiel-Tech-Inf/socha-gui/commit/515aab05d31b13a48f67588b33fef7a66a703225

**Comment by xeruf** [comment]
Replays aus dem Discord:
[undeployed-replays.zip](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/files/3797998/undeployed-replays.zip)
Niklas: "Eine Schülerin hat einen Bug in der GUI gefunden, scheinbar verschwinden alle noch nicht gelegten Steine von Team Blau wenn Rot alle seine Steine abgelegt hat.
Ich konnte das in der neuen GUI Version auch reproduzieren."

**Comment by Yasamato** [comment]
Ich kann da auch nichts machen, siehe:
https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/16797238646fabc889dc943ba0dabaec8d4f6474/src/api/synchronous/GameManagerWorkerInterface.ts#L105-L113
https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/16797238646fabc889dc943ba0dabaec8d4f6474/src/api/synchronous/GameManagerWorkerInterface.ts#L46-L48
Die GUI-kriegt da vom Server einen leeren Array, sobald Rot keine zu platzierende Figuren mehr hat, seltsamerweise nicht andersherum wenn Blau keine Figuren mehr hat.

Im log ist jedoch noch der Array mit undeployed blue enthalten, werden aber durch das Backend nicht mehr übergeben.

**Comment by xeruf** [comment]
Ich habe es doch vorher getestet, das liegt nicht am Server, sondern irgendwo im späteren parsing. Siehe https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/16797238646fabc889dc943ba0dabaec8d4f6474/tests/parserTest.ts

**Comment by Yasamato** [comment]
Ja, das meine ich ja, das geloggte XML ist korrekt, aber beim Parsen geht das schief.

**Comment by xeruf** [comment]
Ich würde für jede involvierte Methode weitere Tests in [parserTest](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/16797238646fabc889dc943ba0dabaec8d4f6474/tests/parserTest.ts) schreiben, um das Problem Stück für Stück einzugrenzen.

**Comment by Yasamato** [comment]
Ich konnte den Fehler auf die Antwort von fetch(url) einschränken in:
https://github.com/CAU-Kiel-Tech-Inf/socha-gui/blob/16797238646fabc889dc943ba0dabaec8d4f6474/src/api/synchronous/GameManagerWorkerInterface.ts#L46-L48

Die erhaltene Antwort hierbei ist ein JSON-String, bei dem schon undeployedblue leer ist.
Dieser JSON-String wird als Stream hierbei vom Server (?) gesendet:
![image](https://user-images.githubusercontent.com/27964795/68240841-e7b20580-000d-11ea-8206-60a98a4568bd.png)

Im console.log wird der Server ganz zu Beginn, jedoch unter einem anderen Port gelistet, ist diese JSON-Kommunikation also GUI-intern?

**Comment by Yasamato** [comment]
Siehe https://github.com/CAU-Kiel-Tech-Inf/socha-gui/tree/debug-stream

**Comment by xeruf** [comment]
Es gibt keine JSON-Kommunikation mit dem Server. Die Kommunikation die du da siehst ist in der GUI zwischen dem synchronous und asynchronous package.

**Comment by Yasamato** [comment]
Der Fehler lag weder am Server, Parsen oder sonst wo.... undeployedRed wurde nur an einer Stelle fehlerhafterweise anstatt undeployedBlue verwendet

**Comment by xeruf** [comment]
Fixed by #103
