### ISSUE TITLE
GUI can't be opened on macOS Catalina

### ISSUE THREAD

**Issue by matthesjh** [CAU-Kiel-Tech-Inf/socha-gui#92]
The current version (20.0.9) of the GUI can't be opened on macOS 10.15.0 Catalina (build 19A583).

The issue is maybe related to [`electron-builder`](https://github.com/electron-userland/electron-builder/) as described in the following Medium post (a workaround is also included).

https://medium.com/cacher-app/getting-your-electron-app-working-on-macos-catalina-10-15-63e53f397da2

**Comment by matthesjh** [comment]
@Xerus2000 Can we get this fixed by updating to a newer `electron-builder` version?

**Comment by matthesjh** [comment]
Are there any news on that issue?

**Comment by Yasamato** [comment]
Könntest du überprüfen @matthesjh, ob mit der neuen Version [2.2.2](https://github.com/CAU-Kiel-Tech-Inf/socha-gui/releases/tag/20.2.2) durch das Update von `electron-builder` das Problem behoben wurde?

**Comment by matthesjh** [comment]
No, it's still there.
