### ISSUE TITLE
Sign and notarize the GUI

### ISSUE THREAD

**Issue by matthesjh** [CAU-Kiel-Tech-Inf/socha-gui#93]
To avoid warnings on recent versions of macOS and to improve the security of the distributed binaries, the GUI should be signed with a *Developer ID* and notarized by Apple. This process can be automated with the build system and `electron-builder`, but requires a paid Apple Developer Program membership.

More information can be found here: https://developer.apple.com/developer-id/

**Comment by Yasamato** [comment]
@SKoschnicke haben wir da eine Möglichkeit auf eine Uni-eigene ID zuzugreifen, welche bereits im Apple Developer Program drinnen ist? Wenn nicht halte ich das Problem momentan für eher zweitrangig.

**Comment by SKoschnicke** [comment]
Nein haben wir nicht. Es ist aber kein Problem, einen entsprechenden Account anzulegen.

Es ist sicher nicht die oberste Prioritaet, aber das Signieren der Releases fuer alle drei Plattformen sollte auch in Angriff genommen werden.

**Comment by Yasamato** [comment]
Generell ist unsere Software nicht sehr vertrauenswürdig wie mir scheint:
![image](https://user-images.githubusercontent.com/27964795/69272282-b4a76e80-0bd6-11ea-9c63-c5b0538c8735.png)

**Comment by matthesjh** [comment]
Signing software that is distributed to customers is very important nowadays. So this should be implemented rather sooner than later!

**Comment by Yasamato** [comment]
Doc für electron-builder: https://www.electron.build/code-signing

**Comment by Yasamato** [comment]
Für windows kann man als open-source beantragen: https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-1022.html

**Comment by Yasamato** [comment]
Dafür müssten wir uns erstmal eine Lizenz anlegen, welche wenn ich das richtig sehe, nicht haben

**Comment by xeruf** [comment]
Projekte wie dieses tracken wir nun intern in Notion
