### ISSUE TITLE
MissMove in SkipMove umbenennen

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-gui#96]
Siehe https://github.com/CAU-Kiel-Tech-Inf/socha/commit/187b62ea3659840ba42b03bdb611adee7e6665e0

Der HumanClient der GUI muss entsprechend angepasst werden, damit er das veraenderte XML sendet.

**Comment by xeruf** [comment]
Done: 4848df3
