### ISSUE TITLE
SkipMove button erscheint nicht, wenn man keinen Zug machen kann

### ISSUE THREAD

**Issue by xeruf** [CAU-Kiel-Tech-Inf/socha-gui#97]
![image](https://user-images.githubusercontent.com/13354331/67625501-470a5b80-f83f-11e9-8dec-7fd06217a862.png)
Spielsteine sind gelb umrandet, gibt aber keine Setzposition

![image](https://user-images.githubusercontent.com/13354331/67625511-5f7a7600-f83f-11e9-8ac5-9a5073393069.png)

**Comment by xeruf** [comment]
![image](https://user-images.githubusercontent.com/13354331/67626061-a91a8f00-f846-11e9-8490-ae841e13818d.png)

**Comment by Yasamato** [comment]
Hm... der Skip-Button kommt jetzt zur erwünschten Zeit und Stelle.... nur bleibt sie da dort.

**Comment by Yasamato** [comment]
Die UI wird auch gecleared, das sprite-object mit dem button wird auch entfernt (= null gesetzt), aber trotzdem weiterhin gezeichnet. Hast du da eine @SKoschnicke?
